---
title: "Orange Yield Empirical Model"
author: "Hannah Garcia & Haley Grant"
date: "5/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# upload packages
library(raster)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(patchwork)
library(janitor)
library(ncdf4)
library(chron)
library(rgdal)
library(here)
```

```{r}
# read in function 
source("orange_yield.R")
```

```{r}
# read in data

all_climate <- read.csv("2578042.csv") # this data set contains data from three stations: Wiley Ridge CA, Oxnard CA, and Oxnard Weather Forecast Office, CA. All of these locations are in the general Oxnard area, which is an important agricultural region. Oranges are known to grow here or in the surrounding areas. 

# tidy data for function

all_climate_tidy <- all_climate %>% 
  clean_names() # all three locations combined, general oxnard area

max_temp <- all_climate_tidy %>% 
  select(date, tmax) # we don't need max temp for model

min_temp <- all_climate_tidy %>% 
  select(date, tmin) %>% # we need min temp for December from year before
  drop_na() %>% 
  group_by(date) %>%# average tmin for repeated dates
  summarize(tmin = mean(tmin)) %>% 
  mutate(month = month(date)) %>% 
  filter(month == "12") %>% # filter only the month of december
  mutate(year = year(date)) %>% 
  group_by(year) %>% 
  summarize(tmin_december = mean(tmin))

precip <- all_climate_tidy %>% 
  select(date, prcp) %>% # we need precip for May  
  drop_na() %>% 
  group_by(date) %>%# average precip for repeated dates
  summarize(prcp = mean(prcp)) %>% 
  mutate(month = month(date)) %>% 
  filter(month == "5") %>% # filter only the month of may
  mutate(year = year(date)) %>% 
  group_by(year) %>% 
  summarize(prcp_may = mean(prcp)) %>% 
  slice(-20) # remove the last year so the dfs match up
  
# slice(2:20) # remove first year so we only use current year for precip and previous year for temp

# Combine dfs
final_df <- merge(precip, min_temp, by = year) #ugh can't get this to work..

```

```{r}
# test the model

result <- orange_anomaly(precip = precip$prcp_may, min_temp = min_temp$tmin_december)
head(result)
view(result)

# make dataframe
# orange_df = tibble(year = result[,1], anomaly= result[,2])

# graph to see what it looks like

```



```{r}
# filename for data
ncname20th <- "b.e11.B20TRC5CNBDRD.f09_g16.102.cam.h0.TS.199001-200512"  
ncfname20th <- paste(ncname20th, ".nc", sep="")
ncname21st <- "b.e11.BRCP85C5CNBDRD.f09_g16.102.cam.h0.TS.208501-210012"  
ncfname21st <- paste(ncname21st, ".nc", sep="")
dname <- "TS"  # this is the name of the variable you want to look at

ncin <- nc_open(ncfname20th)
ncin21st <- nc_open(ncfname21st)

lon <- ncvar_get(ncin,"lon")
nlon <- dim(lon)
lat <- ncvar_get(ncin,"lat")
nlat <- dim(lat)

# Time coordinate for 20th century part of run
time20th <- ncvar_get(ncin,"time")
tunits20th <- ncatt_get(ncin,"time","units")
origin="1/15/1990"
enddate="12/15/2005"
rtime20th <- seq.dates(origin, enddate, by="months")

# Time coordinate for 21st century part of run
origin="1/15/2085"
enddate="12/15/2100"
rtime21st <- seq.dates(origin, enddate, by="months")
```



```{r}
TS20th <- ncvar_get(ncin, "TS")-273.15
TS21st <- ncvar_get(ncin21st, "TS")-273.15

lats=which(lat >= 32 & lat <= 35)
lons=which(lon >= 241 & lon <= 243)

# Regional minimum temperature
tsmin20th <- apply(TS20th[lons,lats,],3,min)
tsmin21st <- apply(TS21st[lons,lats,],3,min)

# Make data frame, store the month of year in the data frame along with temperature information
clim20th <- data.frame(time=rtime20th, tsmin=tsmin20th)
clim20th$season = month(rtime20th)
clim21st <- data.frame(time=rtime21st, tsmin=tsmin21st)
clim21st$season = month(rtime21st)

# Get December values only for minimum temperature
decclim20th = subset(clim20th, clim20th$season==12)
decclim20th$dt = unique(year(rtime20th))
decclim21st = subset(clim21st, clim21st$season==12)
decclim21st$dt = unique(year(rtime21st))

# Apply empirical model: assume no change in efficiency below 15C, -1%/degree C above
fac20=ifelse(decclim20th$tsmin-15 < 0,0,(decclim20th$tsmin-15)*-0.01)+1
fac21=ifelse(decclim21st$tsmin-15 < 0,0,(decclim21st$tsmin-15)*-0.01)+1

# Effect of climate change = ratio of efficiency factors for 21st, 20th century periods
ccfac=mean(fac21)/mean(fac20)
print(ccfac)
```

## Read in Cal-Adapt Data (to-delete)
```{r}
require(raster)
library(here)
library(dplyr)

## ------------------------------------------------------------------------------------
# Precip: read in raster files and convert to points
precip <- list.files(path = here("caladapt_data", "precip"), full.names = TRUE)

prcp_raster <- raster::stack(precip) 

prcp_df <- raster::rasterToPoints(prcp_raster) %>% 
  as.data.frame()

# remove first part of the column names so it is just the date
names(prcp_df) = gsub(pattern = "prcp_flx_ccsm3a2bcsd_", replacement = "", x = names(prcp_df))

# Filter for x and y coordinates in ventura area
prcp_tidy <- prcp_df %>% 
  filter(between(x, -120, -119)) %>% 
  filter(between(y, 34, 35)) #49,

prcp_one_location <- prcp_tidy %>% 
  filter(x == -119.9375) %>% # just chose one location because we do not need 49 points..
  select(dplyr::contains("05")) %>% 
  pivot_longer(cols = 3:33,
               names_to = "year",
               values_to = "value") 

prcp_one_location <- prcp_one_location[ -c(1:2) ] # got rid of x and y because we don't need them


## ---------------------------------------------------------------------------------------
# Tmin
tmin <- list.files(path = here("caladapt_data", "tmin"), full.names = TRUE)

tmin_raster <- raster::stack(tmin) 

tmin_df <- raster::rasterToPoints(tmin_raster) %>% 
  as.data.frame()

names(tmin_df) = gsub(pattern = "tmin_inf_ccsm3a2bcsd_", replacement = "", x = names(tmin_df))

# Filter for Ventura area (roughly)
tmin_tidy <- tmin_df %>% 
  filter(between(x, -120, -119)) %>% 
  filter(between(y, 34, 35)) #49

tmin_one_location <- tmin_tidy %>% 
  filter(x == -119.9375) %>% # just chose one location because we do not need 49 points..
  select(dplyr::contains("12")) %>% 
  pivot_longer(cols = 3:30,
               names_to = "year",
               values_to = "value") 

tmin_one_location <- tmin_one_location[ -c(1:2) ]
```

### CalAdapt Data: read in data and tidy
```{r}
require(raster)
library(here)
library(dplyr)

## ------------------------------------------------------------------------------------
# Precip: read in raster files and convert to points
precip <- list.files(path = here("caladapt_data", "precip"), full.names = TRUE)

prcp_raster <- raster::stack(precip) 

prcp_df <- raster::rasterToPoints(prcp_raster) %>% 
  as.data.frame()

# remove first part of the column names so it is just the date
names(prcp_df) = gsub(pattern = "prcp_flx_ccsm3a2bcsd_", replacement = "", x = names(prcp_df))

## ------------------------------------------------------------------------------------
# Ventura coordinates are: 34.3705° N, 119.1391° W (we'll use -119.9375, 34.9375)
prcp_tidy <- prcp_df %>% 
  filter(between(x, -120, -119)) %>% 
  filter(between(y, 34, 35)

prcp_select <- prcp_tidy %>% 
  filter(x == -119.9375, y == 34.9375) %>% 
  pivot_longer(cols = starts_with("2"),
               names_to = "date",
               values_to = "prcp") %>% 
  mutate(date=ymd(date)) %>% 
  mutate(month = month(date)) %>% 
  filter(month==05) %>% 
  mutate(year=year(date))

prcp_select <- prcp_select[-c(1:4)]

prcp_final <- prcp_select %>% 
  select(year, everything())

prcp_final <- prcp_final[-c(3)] # final dataframe for precip for month of may for every year

## -----------------------------------------------------
# tmin
tmin <- list.files(path = here("caladapt_data", "tmin"), full.names = TRUE)

tmin_raster <- raster::stack(tmin) 

tmin_df <- raster::rasterToPoints(tmin_raster) %>% 
  as.data.frame()

names(tmin_df) = gsub(pattern = "tmin_inf_ccsm3a2bcsd_", replacement = "", x = names(tmin_df))

tmin_tidy <- tmin_df %>% 
  filter(between(x, -120, -119)) %>% 
  filter(between(y, 34, 35))

tmin_select <- tmin_tidy %>% 
  filter(x == -119.9375, y == 34.9375) %>% 
  pivot_longer(cols = starts_with("2"),
               names_to = "date",
               values_to = "tmin") %>% 
  mutate(date=ymd(date)) %>% 
  mutate(month = month(date)) %>% 
  filter(month==12) %>% 
  mutate(year=year(date))

tmin_select <- tmin_select[-c(1:3, 5)]

tmin_final <- tmin_select %>% 
  select(year, everything()) # final dataframe for precip for month of december for every year
```

